### ISSUE TITLE
HMI Status ignored if HMI Level and AudioStreamingState Unchanged

### ISSUE THREAD

**Issue by mrapitis** [smartdevicelink/sdl_android#662] opened 2017-12-20 15:49 UTC
##  **Bug Report**

HMI Status notifications are not being sent to the app when the HMI Level and AudioStreamingState have not changed.  This problem can be easily replicated by entering and exiting the in app menu which causes a change from an HMI Level of FULL, AudioStreamingState of AUDIBLE and systemContext of MENU to HMI Level of FULL, AudioStreamingState of AUDIBLE and systemContext of MAIN.  These notifications are being ignored due to the code linked below:

https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android/src/main/java/com/smartdevicelink/proxy/SdlProxyBase.java#L3029

It looks like the issue was introduced in SDL Core 4.4 during a clean pull request.

**Reproduction Steps**
Register an app with SDL.
Select the in app Menu on the HMI
Take note that no HMI Status is received
Move back to the main view of the app
Take note that no HMI Status is received

**Expected Behavior**

Register an app with SDL.
Select the in app Menu on the HMI
An HMI status of FULL,AUDIBLE,MENU is received.
Move back to the main view of the app
An HMI status of FULL,AUDIBLE,MAIN is received.

**Observed Behavior**
No HMI status when navigating to / from the menu in the app.

**Comment by joeygrover** [comment] 2017-12-20 15:55
It looks like the logic was supposed to be in place and was changed to actually work. However, the logic that it was intended for was not ideal. The logic should simply be pulled out.

**Comment by mrapitis** [comment] 2017-12-20 15:57
Sounds like a plan and a straightforward fix.

**Comment by joeygrover** [comment] 2018-01-31 15:16
Fixed with #673

**Closed by joeygrover** 2018-01-31 15:16 UTC
Labels: bug
