### ISSUE TITLE
onSdlEnabled is called even if app is not connected with SDL enabled device

### ISSUE THREAD

**Issue by mdakram** [smartdevicelink/sdl_android#907] opened 2018-10-23 04:21 UTC
We are using this library to connect our app to ford sync platform. As there is limitation with background services from `Android O(Oreo)` we can not run background service without showing a notifications to the user.

So as in sample we are starting SDLService in `onSdlEnabled`, but this callback we are receiving as soon as app is open and phone's bluetooth is turned on. 

Is there any way we can identify when app is connected to SDL enable device, show that we can show notification then only.

**Comment by BrettyWhite** [comment] 2018-10-23 13:33
Hi @mdakram 

In the future, please follow the issue template. It is there for a reason. What version of SDL Android are you using?

**Comment by mdakram** [comment] 2018-10-24 04:03
@BrettyWhite Sure i will, I am using latest one i.e. 4.7.0

**Comment by BrettyWhite** [comment] 2018-10-24 18:06
Hi, We were unable to reproduce the issue with Hello SDL app on a Ford Sync3 head unit using 4.7.0.

Could you please try to reproduce this using Hello SDL (now packaged with the SDL Android repo) and see if it happens as well? Printing the intent from `onSdlEnabled` might be useful as well.

Until then I'm going to close the issue due to the inability to reproduce it. You may also want to check out our slack channel http://slack.smartdevicelink.com for more help as the guides https://smartdevicelink.com/en/guides/android/getting-started/installation/

Thanks!

**Closed by BrettyWhite** 2018-10-24 18:06 UTC
