### ISSUE TITLE
LockScreenManager Value Checking 

### ISSUE THREAD

**Issue by MikaylaRay44** [smartdevicelink/sdl_android#170] opened 2015-04-24 18:50 UTC
Relevent classes:
com/smartdevicelink/proxy/LockScreenManager

The setHMILevel method does not check against a null input value and can cause a NullPointerException to be thrown. The variable 'hmiVal' needs to be checked before being used.

**Comment by mikeburke106** [comment] 2015-04-26 13:47
This is a duplicate of #143 and was fixed in PR #146.

**Closed** 2015-04-27 13:10 UTC
Labels: bug
