### ISSUE TITLE
Potential NPE in LockScreenManager

### ISSUE THREAD

**Issue by brettywhite** [smartdevicelink/sdl_android#456] opened 2017-04-11 13:46 UTC
Possible NPE in LockScreenManager if hmi level passed in is null.

[reference here](https://github.com/smartdevicelink/sdl_android/blob/master/sdl_android_lib/src/com/smartdevicelink/proxy/LockScreenManager.java#L41-L49)

In case link to code changes:

```
public synchronized void setHMILevel(HMILevel hmiVal)
	{		
		hmiLevel = hmiVal;
		
		if ( (hmiVal.equals(HMILevel.HMI_FULL)) || (hmiVal.equals(HMILevel.HMI_LIMITED)) )
			setUserSelectedStatus(true);
		else if (hmiVal.equals(HMILevel.HMI_NONE))
			setUserSelectedStatus(false);				
	}
```

**Comment by bilal-alsharifi** [comment] 2018-06-01 13:42
The issue is fixed in the current develop branch.

**Closed** 2018-06-01 13:41 UTC
